# Generated by Django 4.1.1 on 2022-09-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_stripe_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='product_stripe_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
